### ISSUE TITLE
Use docker-compose

### ISSUE THREAD

**Issue by jifeon** [redco/goose-starter-kit#2]
It's annoying to rebuild the container each time I modified index.js Need to create folder `app` and move files there, then create `docker-compose.yml` and mark this folder as volume

**Comment by jifeon** [comment]
then remove ugly `run-with-docker.sh`

**Comment by maZahaca** [comment]
sure, i'll provide compose as well

**Comment by maZahaca** [comment]
Fixed in 320fb5dc1c06a74dc165b46d11c2e7a78873c9a2
